# see. http://qiita.com/okamos/items/2259d5c770d51b88d75b

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1 # load in insert mode
if = "has('nvim')"
hook_source = 'source ~/.config/nvim/plugins/deoplete.rc.vim'

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'ruby'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = 'source ~/.config/nvim/plugins/denite.rc.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_event = 'TextYankPost'
on_source = ['denite.nvim']
