tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "neovim/neovim"
brew "autoconf"
brew "automake"
brew "colordiff"
brew "coreutils"
brew "libidn2"
brew "curl", link: true
brew "docker"
brew "docker-compose", link: false
brew "findutils"
brew "gdbm"
brew "gh"
brew "git"
brew "git-lfs"
brew "libffi"
brew "readline"
brew "sqlite"
brew "xz"
brew "glib"
brew "gnu-sed"
brew "gnu-tar"
brew "libtool"
brew "pkg-config"
brew "gnupg"
brew "grep"
brew "htop"
brew "libmagic"
brew "libnfs"
brew "libpq"
brew "libvterm"
brew "libyaml"
brew "lldpd", restart_service: true
brew "mas"
brew "neovim"
brew "nkf"
brew "nmap"
brew "parquet-tools"
brew "protobuf"
brew "pstree"
brew "starship"
brew "tree"
brew "watch"
brew "wget"
brew "zip"
brew "zlib"
brew "zsh"
cask "font-hackgen"
cask "font-hurmit-nerd-font"
cask "google-chrome"
cask "hammerspoon"
cask "jetbrains-toolbox"
cask "karabiner-elements"
mas "1Password 7", id: 1333542190
mas "Fantastical", id: 975937182
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
