tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'neovim/neovim'
tap 'shogogg/cask-atok'
brew 'autoconf'
brew 'automake'
brew 'awscli'
brew 'bdw-gc'
brew 'cmake'
brew 'ctop'
brew 'git'
brew 'docker'
brew 'gdbm'
brew 'gettext'
brew 'htop'
brew 'jemalloc'
brew 'openssl'
brew 'libevent'
brew 'libffi'
brew 'libtermkey'
brew 'libtool'
brew 'libuv'
brew 'libvterm'
brew 'libyaml'
brew 'mas'
brew 'msgpack'
brew 'mysql'
brew 'pcre'
brew 'pcre2'
brew 'pkg-config'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'xz'
brew 'the_silver_searcher'
brew 'tmux'
brew 'unibilium'
brew 'w3m'
brew 'zsh'
brew 'neovim/neovim/neovim'
cask 'alfred'
cask 'atok-passport'
cask 'bartender'
cask 'bettertouchtool'
cask 'clipy'
cask 'contexts'
cask 'flux'
cask 'font-hermit'
cask 'font-hermit-nerd-font-mono'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'hammerspoon'
cask 'iterm2'
cask 'java'
cask 'java7'
cask 'jetbrains-toolbox'
cask 'karabiner-elements'
cask 'kindle'
cask 'slack'
cask 'teensy'
cask 'vivaldi'
mas 'Tweetbot', id: 557168941
mas 'Timing', id: 431511738
mas 'GarageBand', id: 682658836
mas 'iMovie', id: 408981434
mas 'Pages', id: 409201541
mas 'PopClip', id: 445189367
mas 'Keynote', id: 409183694
mas 'LINE', id: 539883307
mas 'Display Menu', id: 549083868
mas 'OmniPlan', id: 1040002810
mas 'Numbers', id: 409203825
