tap "git-time-metric/gtm"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "neovim/neovim"
tap "olafurpg/scalafmt"
tap "osx-cross/avr"
tap "sscotth/sip"
tap "warrensbox/tap"
tap "weaveworks/tap"
brew "gdbm"
brew "openssl"
brew "readline"
brew "autoconf"
brew "automake"
brew "avrdude"
brew "xz"
brew "awscli"
brew "bash"
brew "bdw-gc"
brew "circleci"
brew "colordiff"
brew "coreutils"
brew "ctop"
brew "dfu-programmer"
brew "docker", link: false
brew "libyaml"
brew "docker-compose", link: false
brew "docker-machine", link: false
brew "flyway"
brew "gettext"
brew "pcre2"
brew "git"
brew "git-flow"
brew "git-now"
brew "libevent"
brew "libffi"
brew "gnupg"
brew "gradle"
brew "libtool"
brew "graphviz"
brew "pcre"
brew "grep"
brew "htop"
brew "hub"
brew "iftop"
brew "kubernetes-cli"
brew "kubectx"
brew "libidn2"
brew "libnfs"
brew "unibilium"
brew "libtermkey"
brew "libuv"
brew "libvterm"
brew "luajit"
brew "mas"
brew "maven"
brew "msgpack"
brew "mysql"
brew "neovim"
brew "nkf"
brew "nmap"
brew "thrift"
brew "osquery"
brew "parquet-tools"
brew "pgcli"
brew "pkg-config"
brew "protobuf"
brew "reattach-to-user-namespace"
brew "redis"
brew "teensy_loader_cli"
brew "terraform", link: false
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tree"
brew "w3m"
brew "watch"
brew "wget"
brew "zlib"
brew "zsh"
brew "git-time-metric/gtm/gtm"
brew "olafurpg/scalafmt/scalafmt", args: ["HEAD"]
brew "osx-cross/avr/avr-gcc"
brew "warrensbox/tap/tfswitch"
brew "weaveworks/tap/eksctl"
cask "1password"
cask "1password-cli"
cask "alfred"
cask "bartender"
cask "clipy"
cask "contexts"
cask "docker"
cask "firefox"
cask "flux"
cask "forticlient"
cask "google-chrome"
cask "google-japanese-ime"
cask "hammerspoon"
cask "iterm2"
cask "java"
cask "java8"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "kindle"
cask "mat"
cask "minikube"
cask "paw"
cask "sampler"
cask "skype"
cask "slack"
cask "teensy"
cask "toggl"
cask "vagrant"
cask "virtualbox"
cask "visualvm"
cask "sscotth/sip/totalspaces"
mas "Display Menu", id: 549083868
mas "GarageBand", id: 682658836
mas "Habitify", id: 1140787122
mas "HazeOver", id: 430798174
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PopClip", id: 445189367
mas "Tweetbot", id: 557168941
