# ref. https://raw.githubusercontent.com/alacritty/alacritty/master/alacritty.yml

window:
  decorations: none
  startup_mode: Maximized

scrolling:
  auto_scroll: true

font:
  normal:
    family: Hurmit Nerd Font Mono
    # style: Regular
  bold:
    family: Hurmit Nerd Font Mono
    style: Bold
  italic:
    family: HackGen Console for Powerline
    style: Regular  # TODO: Italic
  bold_italic:
    family: HackGen Console for Powerline
    style: Bold  # TODO: Italic

  size: 14.0

# Colors (Oxide)
colors:
  # Default colors
  primary:
    background: '0x212121'
    foreground: '0xc0c5ce'
    bright_foreground: '0xf3f4f5'

  cursor:
    text: '0x212121'
    cursor: '0xc0c5ce'

  # Normal colors
  normal:
    black:   '0x212121'
    red:     '0xe57373'
    green:   '0xa6bc69'
    yellow:  '0xfac863'
    blue:    '0x6699cc'
    magenta: '0xc594c5'
    cyan:    '0x5fb3b3'
    white:   '0xc0c5ce'

  # Bright colors
  bright:
    black:   '0x5c5c5c'
    red:     '0xe57373'
    green:   '0xa6bc69'
    yellow:  '0xfac863'
    blue:    '0x6699cc'
    magenta: '0xc594c5'
    cyan:    '0x5fb3b3'
    white:   '0xf3f4f5'
background_opacity: 0.7

selection:
  save_to_clipboard: true

cursor:
  style: Beam
  unfocused_hollow: true

live_config_reload: true

mouse:
  hide_when_typing: true

